{{- if and (not .Values.existingSecret) .Values.env.telegramBotToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nclaw.fullname" . }}
  labels:
    {{- include "nclaw.labels" . | nindent 4 }}
type: Opaque
stringData:
  telegram-bot-token: {{ .Values.env.telegramBotToken | quote }}
{{- end }}
